# Application secrets in SSM Parameter Store (SecureString, default aws/ssm key)
# under /<env>/. Values are generated by Terraform and therefore live in the
# Terraform state: access to the state bucket is restricted (infra/bootstrap).
#
# The app host instance role can read only /<env>/* (iam_app_host.tf).

locals {
  db_host = "${aws_db_instance.main.address}:${aws_db_instance.main.port}"
}

# Password for the least-privilege application role. The role itself is
# created by the first migration (DB-001 / MVP-7), which reads it from db_app_url.
resource "random_password" "db_app" {
  length  = 40
  special = false
}

resource "random_bytes" "otp_hmac_secret" {
  length = 32
}

resource "aws_ssm_parameter" "db_migration_url" {
  name        = "/${var.environment}/db_migration_url"
  description = "PostgreSQL URL for migrations (master user)"
  type        = "SecureString"
  value       = "postgresql://${var.db_master_username}:${random_password.db_master.result}@${local.db_host}/${var.db_name}?sslmode=require"
}

resource "aws_ssm_parameter" "db_app_url" {
  name        = "/${var.environment}/db_app_url"
  description = "PostgreSQL URL for the application user (role created in DB-001)"
  type        = "SecureString"
  value       = "postgresql://${var.db_app_username}:${random_password.db_app.result}@${local.db_host}/${var.db_name}?sslmode=require"
}

resource "aws_ssm_parameter" "otp_hmac_secret" {
  name        = "/${var.environment}/otp_hmac_secret"
  description = "32 random bytes (hex) used to HMAC one-time passcodes"
  type        = "SecureString"
  value       = random_bytes.otp_hmac_secret.hex
}
